CREATE TABLE claims (
    claim_id SERIAL PRIMARY KEY,
    "Month" TEXT,
    "WeekOfMonth" INTEGER,
    "DayOfWeek" TEXT,
    "Make" TEXT,
    "AccidentArea" TEXT,
    "DayOfWeekClaimed" TEXT,
    "MonthClaimed" TEXT,
    "WeekOfMonthClaimed" INTEGER,
    "Sex" TEXT,
    "MaritalStatus" TEXT,
    "Age" INTEGER,
    "Fault" TEXT,
    "PolicyType" TEXT,
    "VehicleCategory" TEXT,
    "VehiclePrice" TEXT,
    "FraudFound_P" INTEGER,
    "PolicyNumber" INTEGER,
    "RepNumber" INTEGER,
    "Deductible" INTEGER,
    "DriverRating" INTEGER,
    "Days_Policy_Accident" TEXT,
    "Days_Policy_Claim" TEXT,
    "PastNumberOfClaims" TEXT,
    "AgeOfVehicle" TEXT,
    "AgeOfPolicyHolder" TEXT,
    "PoliceReportFiled" TEXT,
    "WitnessPresent" TEXT,
    "AgentType" TEXT,
    "NumberOfSuppliments" TEXT,
    "AddressChange_Claim" TEXT,
    "NumberOfCars" TEXT,
    "Year" INTEGER,
    "BasePolicy" TEXT
);